/*
 * lotto.cpp
 *
 *  Created on: 15.01.2014
 *      Author: Joro
 *
 *	  @Chapter: 10 - Programming visually
 *		@Descr: This chapter brings together elements from previous chapters to build a complete C++ application in a visual programming environment.
 *	 @Exercise: 1
 *	    @Title: Generating random numbers
 *		@Brief: The graphical application developed on subsequent pages of this book will generate six random numbers within a specific range.
 *				Initially, its functionality can be developed as a console application, then transferred later to illustrate how text-based
 *				programming relates to visual programming.
 *
 *				A pseudo-random number from - 0.0 to 32 767 can be generated by calling the "rand" function from the C++ "<cstdlib>" library. The
 *				range of generated numbers can be set using the % modulus operator specify a maximum value. For example, to generate a whole number
 *				within  the renge of one to nine:
 *
 *								int num = ( (rand() % 9) + 1 );
 *
 *				The numbers generated by "rand" are not truly random, however as it generates the same sequence each time the program is executed. To
 *				generate a different sequence of numbers a "seed" must be specified as an argument to a special "srand" function, such as:
 *
 *								srand(12345);
 *
 *				Although calls to rand will then generate a different sequence of numbers, it is still one that will be repeated each time the
 *				program is executed. To generate a changing sequence the argument to "srand" must besomething other than a static integer. The
 *				solution is to seed the "rand" function using the current time as the argument to "srand" , by calling the time function from
 *				the standard C++ "<ctime>" library. This returns the time as a "time_t" data type, which can be cast as integer data type like
 *				this:
 *
 *								srand( (int) time(0) );
 *
 *				The "time" function returns the number of seconds elapsed since the epoch at midnight (00:00:00), January 1, 1970, and ensures the
 *				generated by "rand" will now appear to be truly random - unless it's called again within the same second.
 *
 *				A series of random numbers generated by "rand" can be used to randomize a consecutive sequence of numbers in array elements. These
 *				could represent the range of numbers to choose from when making a lottery selection - and retrieving the value from the required
 *				number of arrays could represent a random lottery entry. For example, choosing six numbers between one and 49.
 *
 *
 *
 *     @Rember: - You can edit the final loop to output all array elements to see how they are randomized.
 *
 *	   @Beware: - The "srand" function must only be cakked once in a progra -at the start, before any calls to rand.
 *
 *	   @HotTip: - The zero argument to the "time" function is required, and specifies that the returned time need not be stored.
 *
 *
 */

// Specify the library classes to include and a namespace prefix to use
#include <cstdlib>	// Include random support
#include <ctime>	// Include time support
#include <iostream>

using namespace std;

int main(){
	// At the start, declare three trivial integer variables and an array for fifty inteegers
	int i, j, k, nums[50];

	// Seed the random number generator with the current time
	srand( (int) time(0));

	// Fill the array elements 1-49 with integers 1-49
	for (i = 1; i < 50; i++){
		nums[i] = i;
	}

	// Randomize the values in array elements 1-49 (randomly swap the elements of the array between each other)
	for( i = 1 ; i < 50; i++){
		j = (rand() % 49) + 1;
		k = nums[i]; nums[i]  =  nums[j]; nums[j] = k;
	}

	// Now output the values in array elements 1-6
	cout << "You six lucky numbers are: ";
	for( i = 1 ; i < 7; i++) cout << nums[i] << " ";

	return 0;
}


