
/*
	Example 5.: The 'typeid()' operator can be applied to template classes. For example, consider the following program. It creates a
	hierarchy of template classes that store a value. The virtual function 'get_val()' returns a value that is defined by each class. For
	class 'Num', this is the value of the number itself. For 'Square', it is the square of the number, and for 'Sqr_root', it is the square
	root of the number. Objects derived from 'Num' are generated by the 'generator()' function. The 'typeid()' operator is used to determine
	what type of object has been generated.

	Note: The output differs from compiler to compiler. For GCC the output for int is i, for unsigned is j, for example. So, (GCC's) G++
	uses implementation-defined naming for the types, but it also offers the utility c++filt to make them human-readable:
	$ ./test | c++filt -t
*/

// 'typeid()' can be used with templates.
#include <iostream>
#include <typeinfo> // for 'typeid()', 'type_info' and so on.
#include <cmath>
#include <cstdlib> // holding the definitions for EXIT_SUCCESS and EXIT_FAILURE and the exit() function
using namespace std;

template <class T> class Num{
public:
	T x;
	Num(T i){ x = i; }
	virtual T get_val() { return x; }
};

template <class T>
class Square : public Num<T>{
public:
	Square(T i) : Num<T>(i) {}
	T get_val() { return (this->x) * (this->x); }
};

template <class T>
class Sqr_root : public Num<T>{
public:
	Sqr_root(T i) : Num<T>(i) {}
	T get_val() {return sqrt((double)this->x); }
};

// A factory for objects derived from 'Num'.
Num<double> *generator(){

	switch(rand()%2){
		case 0:
			return new Square<double> (rand() % 100);
		case 1:
			return new Sqr_root<double> (rand() % 100);
	}
	return NULL;
}


int main(){
	Num<double> ob1(10), *p1;
	Square<double> ob2(100.0);
	Sqr_root<double> ob3(999.2);
	int i;

	cout << typeid(ob1).name() << endl;
	cout << typeid(ob2).name() << endl;
	cout << typeid(ob3).name() << endl;

	if(typeid(ob2) == typeid(Square<double>))
		cout << "is Square<double>\n";

	p1 = &ob2;

	if(typeid(*p1) != typeid(ob1))
		cout << "Value is: " << p1->get_val();
	cout << "\n\n";
	cout << "Now, generate some Objects.\n";

	for(i=0; i<10; i++){
		p1 = generator(); // get next object

	if(typeid(*p1) == typeid(Square<double>))
		cout << "Square object: ";
	if(typeid(*p1) == typeid(Sqr_root<double>))
		cout << "Sqr_root object: ";

	cout << "Value is: " << p1->get_val();
		cout << endl;
	}

	cout << typeid(float).name();
	
	return EXIT_SUCCESS;
}
/*
	The example shown in main book will not compile.
	Reason: https://goo.gl/s0cazE
	Remedy: https://goo.gl/6lw2sJ
*/


/*
	This program displays the following when ran:

	$ ./Ch12_Sec1_Example5.exe | c++filt -t
	Num<double>
	Square<double>
	Sqr_root<double>
	is Square<double>
	Value is: 10000

	Now, generate some Objects.
	Sqr_root object: Value is: 8.18535
	Square object: Value is: 0
	Sqr_root object: Value is: 4.89898
	Square object: Value is: 3364
	Square object: Value is: 4096
	Sqr_root object: Value is: 6.7082
	Sqr_root object: Value is: 5.19615
	Sqr_root object: Value is: 9.53939
	Sqr_root object: Value is: .48074
	Sqr_root object: Value is: 6


*/
